### ISSUE TITLE
delete vs remove

### ISSUE THREAD

**Issue by wcandillon** [28msec/nolap-report-editor#9]
https://www.dropbox.com/s/bznj6x5ezgyqgu9/Screenshot%202014-06-24%2017.13.25.png

the API is delete but the nickname is removed. @dknochen what are the best practices of when to use delete or remove?

**Comment by dknochen** [comment]
I have no clue to be honest. What is your take on this?

delete really sounds Rest API'ish to me ... about remove I have no opinion. I didn't even think about this when we designed it ... Any suggestion is welcome.

**Comment by ghislainfourny** [comment]
Hi,

I think delete is more filesystem-ish, report is more nosql-collection-ish.
Since we think of it as a drive, I have a slight preference for delete.

Kind regards,
Ghislain

---

Dr. Ghislain Fourny
Director of Research and Development
28msec, Inc.

http://www.28msec.com
http://twitter.com/28msec
